CREATE SCHEMA IF NOT EXISTS customers_db;

CREATE TABLE IF NOT EXISTS customers_db.CUSTOMERS (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    AGE INT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS customers_db.CONTACTS (
    ID BIGINT AUTO_INCREMENT,
    ID_CUSTOMER BIGINT NOT NULL,
    TYPE TINYINT NOT NULL,
    CONTACT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
);